### ISSUE TITLE
The Intents Overview page Using Intents samples don't match the API

### ISSUE THREAD

**Issue by RichLinnell** [FDC3/FDC3#63]
The example to `open` that we have [here](https://fdc3.finos.org/docs/1.0/intents-intro#directing-a-market-data-platform-to-show-a-chart) doesn't match the API that we have defined [here](https://fdc3.finos.org/docs/1.0/api/DesktopAgent#open)

**Comment by nkolba** [comment]
yes, the example in intents should be 'raiseIntent'
