### ISSUE TITLE
Tag v1.0.0 release of FDC3

### ISSUE THREAD

**Issue by brooklynrob** [FDC3/FDC3#71]
I see a 1.0 beta release, https://github.com/FDC3/FDC3/releases/tag/v1.0-beta, but no v1.0.0 yet.

It looks like there have been 52 commits since the v1.0-beta tag. 

Is there a v1.0.0 final release tag pending before the press release? 

And will that release including none, some, or all of the commits to master since the 1.0-beta tag? (See too "Tag code as v1.0 and add release notes" task in https://github.com/FDC3/FDC3/issues/32)

Also ,I noticed the "Release Notes" link on https://fdc3.finos.org/versions is broken as it looks like it depends on there be a "v1.0" tag in github (Note, technically the release tag should be v1.0.0 -- one more ".0" to baseline minor releases)

(For a bit more context, see the foundation guidance re versioning at https://finosfoundation.atlassian.net/wiki/spaces/FINOS/pages/75530371/Released)

**Comment by rikoe** [comment]
I am not sure this merited an issue @brooklynrob 😉. The tag is on the to-do list for the release and will happen. We have to wait until we are sure all the commits are in, some still went in today, and there may still be one or two small changes before Thursday.

**Comment by brooklynrob** [comment]
Thanks @rikoe. Given there have been commits since the ratification vote of 1.0, I wanted to check on (and call out) the tagging and overall tracking of what's changed since that ratification vote. I'd also suggest that there be another final vote done by the PMC (email is fine), once the v1.0.0 release itself is tagged, to affirm the PMC's support and approval to move that tagged release to public release ahead of the press release.

**Comment by brooklynrob** [comment]
Following up here. I want to clarify that I'm less concerned about whether there is a vote per se or not; larger request is that there be some written paper trail that shows and affirms that the entire PMC is aware and understanding that 1) there were changes (commits) between the ratification vote and the release, and 2) the overall nature of those changes (many for example where connected to building the GH pages site. 

The mechanics of how that affirmation happens (acclamation vote on a call recorded in minutes, "I'm good" email, vote by email) are less important than the overall hygiene of making sure the full PMC is aware of what's been tagged and hence what will be released. 

Idea here is not to create more bureaucratic overhead, especially in 11th hour, but rather to affirm that the PMC has approved the release together as a body together.

**Comment by rikoe** [comment]
@brooklynrob there is now a draft v1.0.0 tag ready to be published, waiting on this PR. The intention is for release notes to reference CHANGELOG.md.
