### ISSUE TITLE
API WG Docs links to src and docs are 404 

### ISSUE THREAD

**Issue by finos-admin** [FDC3/FDC3#74]
At the bottom of https://fdc3.finos.org/docs/1.0/api/api-spec there's two links to "src" and "docs" and they give a 404. 

Wonder if it's a leftover from a previous docs implementation and should just be removed.

**Comment by rikoe** [comment]
Thanks, good catch. What is your view on retro-actively changing the 1.0 specification to remove/fix the broken links without changing the wording (which is easy to do)? Otherwise we can fix it in the next version of the docs.
