### ISSUE TITLE
Links returns 404 on https://fdc3.finos.org/docs/1.0/why-fdc3

### ISSUE THREAD

**Issue by mindthegab** [FDC3/FDC3#75]
As per title, on the page https://fdc3.finos.org/docs/1.0/why-fdc3 all instances of the link https://fdc3.finos.org/docs/1.0/apps-and-platforms and the https://fdc3.finos.org/docs/1.0/real-world-use-cases return 404

Let me know how I can help. Happy to send a PR to remove the links but I assume you might have a smarter solution :)

**Comment by rikoe** [comment]
Good catch thanks @mindthegab, I think we should revisit the "Why FDC3" doc. Even in the non-versioned version (https://fdc3.finos.org/docs/next/why-fdc3) where they don't cause a 404, these links go to non-existent pages.
