### ISSUE TITLE
Prior art

### ISSUE THREAD

**Issue by gilescope** [FDC3/FDC3#80]
## Prior Art

Would be good to have a section on prior art in this space on the homepage.

JSON-LD seem to define context and actions, for example: 
https://schema.org/docs/financial.html

ECB using RDF: https://sdw.ecb.europa.eu/datastructure.do?conceptMnemonic=INSTRUMENT_FM&datasetinstanceid=280

Thomson-Reuters using both Turtle-RDF and JSON-LD: http://www.opencalais.com/ (E.g. https://permid.org/1-4296555135 )

Bloomberg Data License seem to support JSON-LD and RDF also.

I'm sure you've spent a lot more time looking into what's out there. It would be great to guide why FDC3 over some competing tech and how you plan to fit in with existing interop standards.

**Comment by rikoe** [comment]
@gilescope thanks for pointing these out. We do not currently have plans to add a prior art section to the website, everything has prior art these days. It may be useful to provide a wider context for FDC3 though, in terms of what else is out there.

It is important to note that the primary focus of FDC3 is to "develop specific protocols and taxonomies to advance the ability of desktop applications in financial workflows to interoperate in a plug-and-play fashion" (see https://fdc3.finos.org/docs/1.0/fdc3-charter), and the examples you mentioned are more related to financial object modelling.

[FINOS](https://finos.org) (which FDC3 falls under), also has a [Financial Objects Program](https://finosfoundation.atlassian.net/wiki/spaces/FO/overview), which is looking at how to represent financial objects, and the current plan is for FDC3 to be mostly a consumer of the definitions they define. Our standard does not currently contain explicit financial object representations, only some examples of how they _could_ be defined with our context data base type.

If you are interested in this area, I would highly encourage you to attend the next meeting of the [Intents and Context Data Working Group](https://finosfoundation.atlassian.net/wiki/spaces/FDC3/pages/85393412/Context+Data+Working+Group), where we discuss questions and proposals around the context data and intents parts of the FDC3 standard.

**Comment by rikoe** [comment]
@gilescope is there anything more we can do to address your concerns, or is it okay to close this issue?
